(() => {
  'use strict';
  let cfg=window.__SAKU_ADMIN_CONFIG__||{};const root=document.getElementById('root'),toastEl=document.getElementById('toast');
  const state={access:null,session:null,admin:null,page:'dashboard',dashboard:null,merchants:[],audit:[],security:[],settings:[],announcements:[]};
  const $=(s,e=document)=>e.querySelector(s),$$=(s,e=document)=>[...e.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const toast=m=>{toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),2500)};
  const approvedOrigins={uat:'https://saku-backend-live-production.up.railway.app',production:'https://saku-backend-production.up.railway.app'};
  const configured=()=>approvedOrigins[String(cfg.environment||'').toLowerCase()]===String(cfg.apiBaseUrl||'').replace(/\/$/,'');
  const plugin=()=>window.Capacitor?.Plugins?.SakuAdminSecureSession;
  let currentTheme='dark';
  const appearance=()=>window.Capacitor?.Plugins?.SakuAppearance;
  function applyTheme(theme){currentTheme=theme==='light'?'light':'dark';document.documentElement.dataset.theme=currentTheme;const meta=document.querySelector('meta[name=\"theme-color\"]');if(meta)meta.setAttribute('content',currentTheme==='dark'?'#111713':'#f5f8f6');return currentTheme}
  async function loadThemePreference(){try{if(appearance()?.get){const out=await appearance().get();return applyTheme(out.theme)}}catch{}return applyTheme('dark')}
  async function setTheme(theme){const next=applyTheme(theme);try{if(appearance()?.set)await appearance().set({theme:next})}catch{}return next}
  function appearancePanel(){const dark=currentTheme==='dark';return `<section class=\"panel\"><div class=\"panelhead\"><h3>Tampilan Aplikasi</h3></div><div class=\"appearance-setting\"><div><b>Mode Gelap</b><small>Preferensi hanya disimpan pada perangkat ini.</small></div><button type=\"button\" class=\"theme-toggle ${dark?'on':''}\" id=\"themeToggle\" role=\"switch\" aria-checked=\"${dark}\"><span></span><em>${dark?'Aktif':'Nonaktif'}</em></button></div></section>`}
  const navIcon=name=>({
    dashboard:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 13h7V4H4zM13 20h7v-9h-7zM4 20h7v-5H4zM13 9h7V4h-7z"/></svg>',
    merchants:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 21v-8h16v8M6 13V8l2-5h8l2 5v5M9 21v-4h6v4M3 8h18"/></svg>',
    users:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
    security:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 5 6v5c0 4.8 2.8 8.2 7 10 4.2-1.8 7-5.2 7-10V6zM9.5 12l1.7 1.7 3.6-4"/></svg>',
    audit:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h12v18H6zM9 7h6M9 11h6M9 15h4"/></svg>',
    settings:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M19 12l2-1-2-3-2 .5-1.5-1.5.5-2-3-2-1 2-2 0-1-2-3 2 .5 2L6.5 8.5 4 8l-1 3 2 1v2l-2 1 1 3 2.5-.5L8 19l-.5 2h3l1-2h2l1 2h3l-.5-2 1.5-1.5 2.5.5 1-3-2-1z"/></svg>'
  }[name]||'');
  const shieldMark=()=>'<svg class="shield-mark" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 5 6v5c0 4.8 2.8 8.2 7 10 4.2-1.8 7-5.2 7-10V6z"/><path d="m9.5 12 1.7 1.7 3.6-4"/></svg>';
  async function saveSession(v){state.session=v;if(plugin()?.save)await plugin().save({sessionToken:v});else sessionStorage.setItem('saku_admin_session',v)}
  async function loadSession(){if(plugin()?.load)return (await plugin().load()).sessionToken||null;return sessionStorage.getItem('saku_admin_session')}
  async function clearSession(){if(plugin()?.clear)await plugin().clear().catch(()=>{});sessionStorage.removeItem('saku_admin_session');state.session=null}
  async function savePendingRevocation(token){if(plugin()?.savePendingRevocation)return plugin().savePendingRevocation({sessionToken:token});sessionStorage.setItem('saku_admin_pending_revocation',token)}
  async function loadPendingRevocation(){if(plugin()?.loadPendingRevocation)return(await plugin().loadPendingRevocation()).sessionToken||null;return sessionStorage.getItem('saku_admin_pending_revocation')}
  async function clearPendingRevocation(){if(plugin()?.clearPendingRevocation)await plugin().clearPendingRevocation().catch(()=>{});sessionStorage.removeItem('saku_admin_pending_revocation')}
  async function readJsonBounded(r,max=1024*1024){const declared=Number(r.headers.get('content-length')||0);if(declared>max)throw new Error('RESPONSE_TOO_LARGE');if(!r.body)return{};const reader=r.body.getReader(),decoder=new TextDecoder();let text='',total=0;while(true){const{value,done}=await reader.read();if(done)break;total+=value.byteLength;if(total>max){reader.cancel().catch(()=>{});throw new Error('RESPONSE_TOO_LARGE')}text+=decoder.decode(value,{stream:true})}text+=decoder.decode();try{return text?JSON.parse(text):{}}catch{return{}}}
  async function api(path,opt={}){if(!configured())throw new Error('API_BELUM_DIKONFIGURASI');const h={'Content-Type':'application/json',...(opt.headers||{})};if(state.access)h.Authorization=`Bearer ${state.access}`;if(state.session)h['X-Admin-Session']=state.session;const r=await fetch(`${cfg.apiBaseUrl.replace(/\/$/,'')}${path}`,{...opt,headers:h});const b=await readJsonBounded(r);if(!r.ok||b.ok===false)throw Object.assign(new Error(b.error||`HTTP_${r.status}`),{status:r.status});return b.data??b}
  function msg(e){return String(e?.message||e||'Gagal').replaceAll('_',' ')}
  const validRole=admin=>['SUPER_ADMIN','ADMIN','SUPPORT','AUDITOR'].includes(String(admin?.role||''));
  async function refresh(){state.session=await loadSession();if(!state.session)return false;try{const d=await api('/api/admin/refresh',{method:'POST'});if(!validRole(d.admin))throw new Error('ADMIN_CONTEXT_REQUIRED');state.access=d.accessToken;state.admin=d.admin;return true}catch{await clearSession();state.access=null;state.admin=null;return false}}
  function login(){root.innerHTML=`<main class="auth"><section class="login"><div class="logo">${shieldMark()}</div><h1>SAKU Admin</h1><p>Platform Management Console · masuk dengan email dan password.</p>${!configured()?'<div class="badconfig">Endpoint backend belum dipasang pada build ini.</div>':''}<form id="loginForm"><div class="field"><label>Email Admin</label><input name="email" type="email" required autocomplete="username"></div><div class="field"><label>Password</label><input name="password" type="password" required autocomplete="current-password"></div><button class="btn primary full">Masuk</button></form></section></main>`;$('#loginForm').onsubmit=async e=>{e.preventDefault();const b=$('button',e.currentTarget);b.disabled=true;try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries()))});if(!validRole(d.admin))throw new Error('ADMIN_CONTEXT_REQUIRED');state.access=d.accessToken;state.admin=d.admin;await saveSession(d.sessionToken);await preload();render();}catch(err){toast(msg(err))}finally{b.disabled=false}}}
  async function preload(){const [d,m]=await Promise.allSettled([api('/api/admin/dashboard'),api('/api/admin/merchants?limit=200')]);if(d.status!=='fulfilled')throw d.reason;state.dashboard=d.value;if(m.status==='fulfilled'){state.merchants=m.value}else{state.merchants=[];setTimeout(()=>toast('Data UMKM belum dapat dimuat. Gunakan Segarkan untuk mencoba lagi.'),50)}}
  function layout(content){root.innerHTML=`<div class="shell"><header class="top"><div class="brand"><div class="logo">${shieldMark()}</div><div><strong>SAKU Admin</strong><small>${esc(state.admin?.role||'Secure session')}</small></div></div><button class="logout" id="logout">Keluar</button></header><main class="main">${content}</main><nav class="nav">${[['dashboard','Ringkas'],['merchants','UMKM'],['users','User'],['security','Security'],['settings','Setting']].map(([p,l])=>`<button data-page="${p}" class="${state.page===p?'active':''}"><b>${navIcon(p)}</b><span>${l}</span></button>`).join('')}</nav></div><div id="portal"></div>`;$$('.nav button').forEach(b=>b.onclick=async()=>{state.page=b.dataset.page;await renderPage()});$('#logout').onclick=logout}
  function render(){renderPage()}
  async function renderPage(){try{if(state.page==='dashboard')dashboardPage();else if(state.page==='merchants')merchantsPage();else if(state.page==='users')await usersPage();else if(state.page==='security')await securityPage();else await settingsPage()}catch(e){toast(msg(e))}}
  function dashboardPage(){const d=state.dashboard||{};layout(`<div class="hero"><div><h2>Platform Dashboard</h2><p>Ringkasan operasional lintas merchant.</p></div><button class="btn secondary" id="refresh">Segarkan</button></div><div class="metrics"><div class="metric"><small>Merchant</small><b>${Number(d.merchants||0)}</b></div><div class="metric"><small>Aktif</small><b>${Number(d.activeMerchants||0)}</b></div><div class="metric"><small>User aktif</small><b>${Number(d.users||0)}</b></div><div class="metric"><small>Session aktif</small><b>${Number(d.activeSessions||0)}</b></div></div><section class="panel"><div class="panelhead"><h3>Health Snapshot</h3></div><div class="row"><b>Transaksi hari ini</b><span>${Number(d.transactionsToday||0)}</span></div><div class="row"><b>Media storage</b><span>${formatBytes(d.mediaBytes||0)}</span></div><div class="row"><b>Security critical 24h</b><span>${Number(d.criticalSecurity24h||0)}</span></div><div class="row"><b>Merchant suspended</b><span>${Number(d.suspendedMerchants||0)}</span></div></section>`);$('#refresh').onclick=async()=>{state.dashboard=await api('/api/admin/dashboard');dashboardPage();toast('Dashboard diperbarui')}}
  function merchantsPage(){layout(`<div class="hero"><div><h2>Merchant Management</h2><p>Governance akun usaha dan session.</p></div></div><input class="search" id="search" placeholder="Cari nama atau email..."><div class="list" id="merchantList"></div>`);const draw=()=>{const q=$('#search').value.toLowerCase().trim();const arr=state.merchants.filter(m=>!q||String(m.name).toLowerCase().includes(q)||String(m.email).toLowerCase().includes(q));$('#merchantList').innerHTML=arr.length?arr.map(m=>`<article class="item" data-id="${esc(m.id)}"><div class="itemtop"><div><strong>${esc(m.name)}</strong><small>${esc(m.email)} · ${Number(m.user_count||0)} user · ${Number(m.active_sessions||0)} session</small></div><span class="badge ${m.status==='SUSPENDED'?'suspended':''}">${esc(m.status)}</span></div><div class="actions"><button class="tiny detail">Detail</button><button class="tiny status">${m.status==='SUSPENDED'?'Aktifkan':'Suspend'}</button><button class="tiny revoke">Revoke Sessions</button></div></article>`).join(''):'<div class="panel">Tidak ada merchant.</div>';$$('.detail').forEach(b=>b.onclick=()=>merchantDetail(b.closest('.item').dataset.id));$$('.status').forEach(b=>b.onclick=()=>statusSheet(b.closest('.item').dataset.id));$$('.revoke').forEach(b=>b.onclick=()=>revokeSheet(b.closest('.item').dataset.id));};$('#search').oninput=draw;draw()}
  async function merchantDetail(id){const [d,users,tx,media]=await Promise.all([api(`/api/admin/merchants/${id}`),api(`/api/admin/merchants/${id}/users?limit=100`),api(`/api/admin/merchants/${id}/transactions?limit=50`),api(`/api/admin/merchants/${id}/media?limit=50`)]);const m=d.merchant||{};sheet(`Merchant: ${esc(m.name)}`,`<div class="row"><b>Status</b><span>${esc(m.status)}</span></div><div class="row"><b>Email</b><span>${esc(m.email)}</span></div><div class="row"><b>User</b><span>${users.length}</span></div><div class="row"><b>Session aktif</b><span>${Number(d.activeSessions||0)}</span></div><div class="row"><b>Media</b><span>${formatBytes(d.mediaBytes||0)}</span></div><div class="panelhead" style="margin-top:16px"><h3>User</h3></div>${users.map(u=>`<div class="row"><div><b>${esc(u.name)}</b><small>${esc(u.email)}</small></div><button class="tiny usertoggle" data-user="${u.id}" data-active="${u.is_active}">${u.is_active?'Suspend':'Aktifkan'}</button></div>`).join('')}<div class="panelhead" style="margin-top:16px"><h3>Transaksi terbaru</h3></div>${tx.slice(0,12).map(t=>`<div class="row"><div><b>${esc(t.invoice_number)}</b><small>${new Date(t.created_at).toLocaleString('id-ID')}</small></div><span>${rupiah(t.total_amount)}</span></div>`).join('')||'<small>Belum ada transaksi.</small>'}<div class="panelhead" style="margin-top:16px"><h3>Media</h3></div><div class="row"><b>Jumlah object</b><span>${media.length}</span></div>`);$$('.usertoggle').forEach(b=>b.onclick=()=>userStatusSheet(b.dataset.user,b.dataset.active==='true',id))}
  function statusSheet(id){const m=state.merchants.find(x=>x.id===id),next=m.status==='SUSPENDED'?'ACTIVE':'SUSPENDED';sheet(`${next==='ACTIVE'?'Aktifkan':'Suspend'} Merchant`,reasonForm('statusForm',`Status akan diubah menjadi ${next}.`));$('#statusForm').onsubmit=async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');try{await api(`/api/admin/merchants/${id}/status`,{method:'POST',body:JSON.stringify({status:next,reason})});await reloadMerchants();closeSheet();merchantsPage();toast('Status merchant diperbarui')}catch(err){toast(msg(err))}}}
  function revokeSheet(id){sheet('Revoke Semua Session',reasonForm('revokeForm','Semua perangkat merchant akan diminta login ulang.'));$('#revokeForm').onsubmit=async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');try{const r=await api(`/api/admin/merchants/${id}/revoke-sessions`,{method:'POST',body:JSON.stringify({reason})});await reloadMerchants();closeSheet();toast(`${Number(r.revoked||0)} session dicabut`)}catch(err){toast(msg(err))}}}
  function userStatusSheet(user,active,merchant){sheet(active?'Suspend User':'Aktifkan User',reasonForm('userStatus','Perubahan ini tercatat pada audit log.'));$('#userStatus').onsubmit=async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');try{await api(`/api/admin/users/${user}/status`,{method:'POST',body:JSON.stringify({active:!active,reason})});closeSheet();await merchantDetail(merchant);toast('Status user diperbarui')}catch(err){toast(msg(err))}}}
  function reasonForm(id,text){return `<form id="${id}"><p style="font-size:9px;color:var(--muted)">${text}</p><div class="field"><label>Alasan (wajib)</label><textarea name="reason" required minlength="5" maxlength="500"></textarea></div><div class="sheetactions"><button type="button" class="btn secondary" data-close>Batal</button><button class="btn primary">Konfirmasi</button></div></form>`}
  async function reloadMerchants(){state.merchants=await api('/api/admin/merchants?limit=200');state.dashboard=await api('/api/admin/dashboard')}
  async function usersPage(){
    const groups=await Promise.all(state.merchants.map(async m=>{
      try{return (await api(`/api/admin/merchants/${m.id}/users?limit=200`)).map(u=>({...u,merchant_name:m.name}));}
      catch{return [];}
    }));
    const rows=groups.flat();
    layout(`<div class="hero"><div><h2>User Platform</h2><p>Pengguna merchant yang terhubung ke platform.</p></div></div><section class="panel"><div class="list">${rows.length?rows.map(u=>`<div class="item"><div class="itemtop"><div><strong>${esc(u.name)}</strong><small>${esc(u.email)} · ${esc(u.merchant_name||'UMKM')}</small></div><span class="badge ${u.is_active?'':'suspended'}">${u.is_active?'ACTIVE':'BLOCKED'}</span></div><div class="actions"><button class="tiny global-user-toggle" data-user="${esc(u.id)}" data-active="${u.is_active}">${u.is_active?'Suspend':'Aktifkan'}</button></div></div>`).join(''):'Belum ada user.'}</div></section>`);
    $$('.global-user-toggle').forEach(b=>b.onclick=()=>globalUserStatusSheet(b.dataset.user,b.dataset.active==='true'));
  }
  function globalUserStatusSheet(user,active){
    sheet(active?'Suspend User':'Aktifkan User',reasonForm('globalUserStatus','Perubahan ini tercatat pada audit log.'));
    $('#globalUserStatus').onsubmit=async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');try{await api(`/api/admin/users/${user}/status`,{method:'POST',body:JSON.stringify({active:!active,reason})});closeSheet();await usersPage();toast('Status user diperbarui')}catch(err){toast(msg(err))}};
  }

  async function securityPage(){
    const [security,audit]=await Promise.all([api('/api/admin/security?limit=150'),api('/api/admin/audit?limit=150')]);
    state.security=security;state.audit=audit;
    layout(`<div class="hero"><div><h2>Security Center</h2><p>Event keamanan dan audit administratif terbaru.</p></div></div><section class="panel"><div class="panelhead"><h3>Security Event</h3></div><div class="list">${state.security.length?state.security.map(e=>`<div class="item"><div class="itemtop"><div><strong>${esc(e.event_type)}</strong><small>${new Date(e.created_at).toLocaleString('id-ID')} · ${esc(e.merchant_id||'platform')}</small></div><span class="badge ${e.severity==='CRITICAL'?'suspended':e.severity==='WARNING'?'warn':''}">${esc(e.severity)}</span></div></div>`).join(''):'Tidak ada event.'}</div></section><section class="panel"><div class="panelhead"><h3>Audit Trail</h3></div><div class="list">${state.audit.length?state.audit.map(a=>`<div class="item"><strong>${esc(a.action)}</strong><small>${esc(a.target_type)} ${esc(a.target_id||'')} · ${new Date(a.created_at).toLocaleString('id-ID')}</small>${a.reason?`<small>Alasan: ${esc(a.reason)}</small>`:''}</div>`).join(''):'Belum ada audit event.'}</div></section>`)
  }
  async function auditPage(){state.audit=await api('/api/admin/audit?limit=150');layout(`<div class="hero"><div><h2>Immutable Audit Trail</h2><p>Aktivitas administratif yang tercatat server-side.</p></div></div><section class="panel"><div class="list">${state.audit.length?state.audit.map(a=>`<div class="item"><strong>${esc(a.action)}</strong><small>${esc(a.target_type)} ${esc(a.target_id||'')} · ${new Date(a.created_at).toLocaleString('id-ID')}</small>${a.reason?`<small>Alasan: ${esc(a.reason)}</small>`:''}</div>`).join(''):'Belum ada audit event.'}</div></section>`)}
  async function settingsPage(){const [settings,ann]=await Promise.all([api('/api/admin/settings'),api('/api/admin/announcements?limit=100')]);state.settings=settings;state.announcements=ann;layout(`<div class="hero"><div><h2>Platform Settings</h2><p>Feature flags, maintenance, pengumuman, dan preferensi tampilan.</p></div><button class="btn primary" id="announce">Pengumuman</button></div>${appearancePanel()}<section class="panel"><div class="panelhead"><h3>Settings</h3></div>${settings.length?settings.map(s=>`<div class="row"><div><b>${esc(s.key)}</b><small>${esc(JSON.stringify(s.value))}</small></div><button class="tiny setting" data-key="${esc(s.key)}">Ubah</button></div>`).join(''):'<small>Belum ada platform setting.</small>'}</section><section class="panel"><div class="panelhead"><h3>Pengumuman</h3></div>${ann.length?ann.map(a=>`<div class="item"><strong>${esc(a.title)}</strong><small>${esc(a.audience)} · ${new Date(a.created_at).toLocaleString('id-ID')}</small><small>${esc(a.message)}</small></div>`).join(''):'<small>Belum ada pengumuman.</small>'}</section>`);$('#announce').onclick=announceSheet;$('#themeToggle').onclick=async()=>{const next=await setTheme(currentTheme==='dark'?'light':'dark');await settingsPage();toast(next==='dark'?'Mode gelap diaktifkan':'Mode gelap dinonaktifkan')};$$('.setting').forEach(b=>b.onclick=()=>settingSheet(b.dataset.key,settings.find(x=>x.key===b.dataset.key)?.value))}
  function settingSheet(key,value){sheet(`Setting: ${esc(key)}`,`<form id="settingForm"><div class="field"><label>JSON value</label><textarea name="value" required>${esc(JSON.stringify(value??false,null,2))}</textarea></div><div class="field"><label>Alasan</label><textarea name="reason" required minlength="5"></textarea></div><button class="btn primary full">Simpan</button></form>`);$('#settingForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);let value;try{value=JSON.parse(f.get('value'))}catch{return toast('JSON tidak valid')}try{await api(`/api/admin/settings/${encodeURIComponent(key)}`,{method:'PUT',body:JSON.stringify({value,reason:f.get('reason')})});closeSheet();await settingsPage();toast('Setting diperbarui')}catch(err){toast(msg(err))}}}
  function announceSheet(){sheet('Buat Pengumuman',`<form id="annForm"><div class="field"><label>Judul</label><input name="title" required minlength="3"></div><div class="field"><label>Pesan</label><textarea name="message" required minlength="5"></textarea></div><div class="field"><label>Audience</label><select name="audience"><option value="ALL_MERCHANTS">Semua Merchant</option><option value="TARGETED">Merchant tertentu</option></select></div><div class="field"><label>Merchant ID (opsional)</label><input name="merchantId"></div><button class="btn primary full">Terbitkan</button></form>`);$('#annForm').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget).entries());if(!o.merchantId)o.merchantId=null;try{await api('/api/admin/announcements',{method:'POST',body:JSON.stringify(o)});closeSheet();await settingsPage();toast('Pengumuman dibuat')}catch(err){toast(msg(err))}}}
  function sheet(title,html){let p=$('#portal');if(!p){p=document.createElement('div');p.id='portal';document.body.appendChild(p)}p.innerHTML=`<div class="sheetback"><div class="sheet"><h3>${title}</h3>${html}</div></div>`;p.querySelector('.sheetback').onclick=e=>{if(e.target.classList.contains('sheetback'))closeSheet()};$$('[data-close]',p).forEach(b=>b.onclick=closeSheet)}function closeSheet(){const p=$('#portal');if(p)p.innerHTML=''}
  async function retryPendingRevocation(){const pending=await loadPendingRevocation();if(!pending)return;const active=state.session;state.session=pending;try{await api('/api/admin/logout',{method:'POST'});await clearPendingRevocation()}catch{}finally{state.session=active}}
  async function logout(){const session=state.session;let revoked=false;try{await api('/api/admin/logout',{method:'POST'});revoked=true}catch{if(session)await savePendingRevocation(session)}if(revoked)await clearPendingRevocation();await clearSession();state.access=null;state.admin=null;login();if(!revoked)toast('Keluar lokal berhasil. Pencabutan sesi server akan dicoba kembali.')}
  const formatBytes=n=>{n=Number(n||0);if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(1)} GB`};
  const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
  async function boot(){await loadThemePreference();if(!configured() && window.Capacitor?.Plugins?.SakuRuntimeConfig?.get){try{cfg={...cfg,...await window.Capacitor.Plugins.SakuRuntimeConfig.get()}}catch{}}if(!configured()){login();return}try{await retryPendingRevocation();if(await refresh()){await preload();render()}else login()}catch{await clearSession();login()}}
  boot();
})();
