@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class, androidx.compose.foundation.ExperimentalFoundationApi::class)
package com.saku.umkm

import android.content.Context
import android.provider.Settings
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.grid.GridCells
import androidx.compose.foundation.lazy.grid.LazyVerticalGrid
import androidx.compose.foundation.lazy.grid.items
import androidx.compose.foundation.pager.HorizontalPager
import androidx.compose.foundation.pager.rememberPagerState
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.text.NumberFormat
import java.util.Locale

private val S=RoundedCornerShape(12.dp);private val M=RoundedCornerShape(16.dp);private val L=RoundedCornerShape(22.dp)
private fun rupiah(v:Long)="Rp "+NumberFormat.getNumberInstance(Locale("id","ID")).format(v)

@Composable fun SakuRoot(vm:SakuViewModel){val root by vm.root.collectAsStateWithLifecycle();val f by vm.flags.collectAsStateWithLifecycle();when(val r=root){RootState.Booting->BrandedLoading("Menyiapkan ruang kerja usaha Anda");is RootState.Auth->AuthScreen(r,f.loading,vm);is RootState.Onboarding->OnboardingScreen(r,vm);is RootState.Ready->MainShell(r.snapshot,f,vm);is RootState.Fatal->FullState(Icons.Outlined.CloudOff,"SAKU belum dapat dibuka",r.message,"Coba lagi",vm::boot)}}

@Composable private fun AuthScreen(state:RootState.Auth,loading:Boolean,vm:SakuViewModel){var name by remember(state.register){mutableStateOf("")};var business by remember(state.register){mutableStateOf("")};var email by remember(state.register){mutableStateOf("")};var pass by remember(state.register){mutableStateOf("")};Column(Modifier.fillMaxSize().safeDrawingPadding().verticalScroll(rememberScrollState()).padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.height(22.dp));WalletMark(74.dp);Spacer(Modifier.height(16.dp));Text("SAKU",fontSize=30.sp,fontWeight=FontWeight.Bold);Text("Transaksi Mudah, Kreatif, Unggul.",fontSize=13.sp,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(28.dp));SakuCard{Text(if(state.register)"Buat akun usaha" else "Masuk ke SAKU",fontSize=22.sp,fontWeight=FontWeight.SemiBold);Spacer(Modifier.height(6.dp));Text(if(state.register)"Mulai kelola usaha dengan alur ringkas dan aman." else "Lanjutkan pengelolaan usaha Anda.",fontSize=12.sp,color=MaterialTheme.colorScheme.onSurfaceVariant);state.message?.let{Spacer(Modifier.height(12.dp));InlineMessage(it)};Spacer(Modifier.height(12.dp));if(state.register){Field(name,{name=it},"Nama pemilik",Icons.Outlined.Person);Spacer(Modifier.height(10.dp));Field(business,{business=it},"Nama usaha",Icons.Outlined.Storefront);Spacer(Modifier.height(10.dp))};Field(email,{email=it},"Email",Icons.Outlined.Email,KeyboardType.Email);Spacer(Modifier.height(10.dp));Field(pass,{pass=it},"Password",Icons.Outlined.Lock,password=true);Spacer(Modifier.height(16.dp));Button(onClick={if(state.register)vm.register(name,business,email,pass)else vm.login(email,pass)},enabled=!loading&&email.isNotBlank()&&pass.isNotBlank()&&(!state.register||(name.length>=2&&business.length>=2&&pass.length>=12)),modifier=Modifier.fillMaxWidth().heightIn(min=52.dp),shape=M){if(loading){CircularProgressIndicator(Modifier.size(18.dp),strokeWidth=2.dp,color=MaterialTheme.colorScheme.onPrimary);Spacer(Modifier.width(8.dp))};Text(if(state.register)"Daftar & lanjutkan" else "Masuk")};TextButton(onClick={vm.switchAuth(!state.register)},modifier=Modifier.align(Alignment.CenterHorizontally)){Text(if(state.register)"Sudah punya akun? Masuk" else "Belum punya akun? Daftar")}}}}

@Composable private fun OnboardingScreen(root:RootState.Onboarding,vm:SakuViewModel){val s=root.state;val results by vm.kbli.collectAsStateWithLifecycle();val searching by vm.kbliLoading.collectAsStateWithLifecycle();Column(Modifier.fillMaxSize().safeDrawingPadding().padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){WalletMark(38.dp);Spacer(Modifier.width(10.dp));Column{Text("SAKU",fontWeight=FontWeight.Bold);Text("Pengaturan awal usaha",fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}};Spacer(Modifier.height(18.dp));StepBar(s.step);Spacer(Modifier.height(20.dp));root.message?.let{InlineMessage(it);Spacer(Modifier.height(10.dp))};when(s.step){"country"->SimpleStep("LOKASI USAHA","Pilih negara","Negara menentukan klasifikasi resmi yang digunakan SAKU.","Indonesia · KBLI 2025"){vm.advanceSimpleOnboarding("country-confirm","ID",org.json.JSONObject().put("language","id"))};"country-confirm"->SimpleStep("KONFIRMASI","Usaha Anda berada di Indonesia?","SAKU menggunakan KBLI 2025 sebagai klasifikasi canonical.","Indonesia"){vm.advanceSimpleOnboarding("business","ID")};"business"->BusinessStep(s,vm);"classification"->ClassificationStep(s,results,searching,vm);"owner"->OwnerStep(s,vm);"consent"->ConsentStep(root.loading,vm);else->BrandedLoading("Menyiapkan dashboard dan preferensi usaha")}}}
@Composable private fun StepBar(step:String){val steps=listOf("country","country-confirm","business","classification","owner","consent","provisioning");val idx=steps.indexOf(step).coerceAtLeast(0);Row(horizontalArrangement=Arrangement.spacedBy(5.dp)){steps.forEachIndexed{i,_->Box(Modifier.weight(1f).height(4.dp).clip(CircleShape).background(if(i<=idx)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.surfaceVariant))}}}
@Composable private fun SimpleStep(kicker:String,title:String,body:String,value:String,next:()->Unit){Column(verticalArrangement=Arrangement.spacedBy(14.dp)){Kicker(kicker);Text(title,fontSize=28.sp,fontWeight=FontWeight.SemiBold);Text(body,color=MaterialTheme.colorScheme.onSurfaceVariant);SakuCard{Row(verticalAlignment=Alignment.CenterVertically){Icon(Icons.Outlined.Language,null,tint=MaterialTheme.colorScheme.primary);Spacer(Modifier.width(12.dp));Text(value,Modifier.weight(1f),fontWeight=FontWeight.SemiBold);Icon(Icons.Outlined.CheckCircle,null,tint=MaterialTheme.colorScheme.primary)}};Button(next,Modifier.fillMaxWidth().heightIn(min=52.dp),shape=M){Text("Lanjutkan")}}}
@Composable private fun BusinessStep(s:OnboardingState,vm:SakuViewModel){var name by remember{mutableStateOf(s.business.name)};var phone by remember{mutableStateOf(s.business.phoneNumber)};var address by remember{mutableStateOf(s.business.address)};var bio by remember{mutableStateOf(s.business.bio)};Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(11.dp)){Kicker("DATA USAHA");Text("Ceritakan usaha Anda",fontSize=27.sp,fontWeight=FontWeight.SemiBold);Text("Informasi ini digunakan pada dashboard dan laporan.",color=MaterialTheme.colorScheme.onSurfaceVariant);Field(name,{name=it},"Nama usaha",Icons.Outlined.Storefront);Field(phone,{phone=it},"Nomor telepon",Icons.Outlined.Phone,KeyboardType.Phone);Field(address,{address=it},"Alamat usaha",Icons.Outlined.LocationOn,single=false);Field(bio,{bio=it},"Tentang usaha",Icons.Outlined.Description,single=false);Button({vm.saveBusiness(name,phone,address,bio)},enabled=name.trim().length>=2,modifier=Modifier.fillMaxWidth().heightIn(min=52.dp),shape=M){Text("Lanjutkan")}}}
@Composable private fun ClassificationStep(s:OnboardingState,results:List<KbliEntry>,loading:Boolean,vm:SakuViewModel){var q by remember{mutableStateOf("")};Column(Modifier.fillMaxSize(),verticalArrangement=Arrangement.spacedBy(10.dp)){Kicker("KLASIFIKASI");Text("Jenis usaha Anda",fontSize=27.sp,fontWeight=FontWeight.SemiBold);Field(q,{q=it;vm.searchKbli(it)},"Cari: angkringan, batik, laundry…",Icons.Outlined.Search);s.primary?.let{AssistChip(onClick={},label={Text("Utama · ${it.code} ${it.title}",maxLines=1)})};if(s.secondary.isNotEmpty())LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){items(s.secondary){c->InputChip(selected=true,onClick={vm.selectClassification(KbliEntry(c.code,c.title,""),false)},label={Text(c.code)})}};if(loading)LinearProgressIndicator(Modifier.fillMaxWidth());LazyColumn(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(7.dp)){if(q.isNotBlank()&&results.isEmpty()&&!loading)item{EmptyCompact(Icons.Outlined.SearchOff,"Usaha belum ditemukan","Coba kata yang lebih umum atau nama aktivitas usaha.")};items(results,key={it.code}){x->Surface(shape=M,color=MaterialTheme.colorScheme.surface,border=androidx.compose.foundation.BorderStroke(1.dp,MaterialTheme.colorScheme.outlineVariant),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){Text("${x.code} · ${x.title}",fontSize=12.sp,fontWeight=FontWeight.SemiBold);Text(x.description,fontSize=10.sp,color=MaterialTheme.colorScheme.onSurfaceVariant,maxLines=2);Row{TextButton(onClick={vm.selectClassification(x,true)}){Text("Jadikan utama")};TextButton(onClick={vm.selectClassification(x,false)}){Text("Tambah sekunder")}}}}}};Button(vm::persistClassification,enabled=s.primary!=null,modifier=Modifier.fillMaxWidth().heightIn(min=52.dp),shape=M){Text("Lanjutkan")}}}
@Composable private fun OwnerStep(s:OnboardingState,vm:SakuViewModel){var name by remember{mutableStateOf(s.owner.name)};Column(verticalArrangement=Arrangement.spacedBy(12.dp)){Kicker("PEMILIK");Text("Siapa yang mengelola usaha?",fontSize=27.sp,fontWeight=FontWeight.SemiBold);Field(name,{name=it},"Nama pemilik / pengelola",Icons.Outlined.Person);Button({vm.saveOwner(name)},enabled=name.trim().length>=2,modifier=Modifier.fillMaxWidth().heightIn(min=52.dp),shape=M){Text("Lanjutkan")}}}
@Composable private fun ConsentStep(loading:Boolean,vm:SakuViewModel){var terms by remember{mutableStateOf(false)};var privacy by remember{mutableStateOf(false)};Column(verticalArrangement=Arrangement.spacedBy(12.dp)){Kicker("PERSETUJUAN");Text("Satu langkah terakhir",fontSize=27.sp,fontWeight=FontWeight.SemiBold);Text("Tinjau persetujuan sebelum akun diprovisi.",color=MaterialTheme.colorScheme.onSurfaceVariant);CheckRow("Saya menyetujui Syarat & Ketentuan",terms){terms=it};CheckRow("Saya memahami Kebijakan Privasi",privacy){privacy=it};Button(vm::completeOnboarding,enabled=terms&&privacy&&!loading,modifier=Modifier.fillMaxWidth().heightIn(min=52.dp),shape=M){if(loading){CircularProgressIndicator(Modifier.size(18.dp),strokeWidth=2.dp);Spacer(Modifier.width(8.dp))};Text("Selesaikan pengaturan")}}}
@Composable private fun CheckRow(label:String,checked:Boolean,on:(Boolean)->Unit){Surface(shape=M,color=MaterialTheme.colorScheme.surface){Row(Modifier.fillMaxWidth().padding(10.dp),verticalAlignment=Alignment.CenterVertically){Checkbox(checked,on);Text(label,fontSize=12.sp)}}}

@Composable private fun MainShell(s:AppSnapshot,f:UiFlags,vm:SakuViewModel){
    var accountOpen by remember{mutableStateOf(false)}
    Scaffold(
        topBar={TopAppBar(
            navigationIcon={if(accountOpen){IconButton({accountOpen=false}){Icon(Icons.Outlined.ArrowBack,"Kembali")}}},
            title={Column{Text(if(accountOpen)"Profil & pengaturan" else s.merchant.name.ifBlank{"SAKU UMKM"},fontSize=15.sp,fontWeight=FontWeight.SemiBold);Text(if(accountOpen)s.user.email else s.merchant.businessCategory.ifBlank{"Ruang kerja usaha"},fontSize=10.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}},
            actions={if(!accountOpen){IconButton({vm.refreshAll()}){Icon(Icons.Outlined.Refresh,"Segarkan")};IconButton({accountOpen=true}){Icon(Icons.Outlined.AccountCircle,"Buka profil dan pengaturan")}}}
        )},
        bottomBar={if(!accountOpen)NavigationBar{navItems.forEach{(p,label,icon)->NavigationBarItem(selected=f.page==p,onClick={vm.setPage(p)},icon={Icon(icon,label)},label={Text(label,fontSize=9.sp)})}}}
    ){pad->Box(Modifier.fillMaxSize().padding(pad)){
        if(accountOpen)AccountScreen(s,f,vm)else when(f.page){AppPage.DASHBOARD->DashboardScreen(s,vm);AppPage.CASHIER->CashierScreen(s,f,vm);AppPage.PRODUCTS->ProductsScreen(s,f,vm);AppPage.REPORT->ReportScreen(s,f,vm)}
        if(f.loading)LinearProgressIndicator(Modifier.fillMaxWidth().align(Alignment.TopCenter))
        f.message?.let{Surface(shape=M,color=MaterialTheme.colorScheme.inverseSurface,modifier=Modifier.align(Alignment.BottomCenter).padding(12.dp)){Text(it,Modifier.padding(horizontal=14.dp,vertical=10.dp),color=MaterialTheme.colorScheme.inverseOnSurface,fontSize=11.sp)}}
    }}
}
private val navItems=listOf(Triple(AppPage.DASHBOARD,"Dashboard",Icons.Outlined.Home),Triple(AppPage.CASHIER,"Kasir",Icons.Outlined.PointOfSale),Triple(AppPage.PRODUCTS,"Produk",Icons.Outlined.Inventory2),Triple(AppPage.REPORT,"Laporan",Icons.Outlined.Analytics))

@Composable private fun DashboardScreen(s:AppSnapshot,vm:SakuViewModel){LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),contentPadding=PaddingValues(bottom=20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Hero("BERANDA","Ringkasan hari ini","Pantau penjualan dan kondisi usaha.")};item{MetricGrid(listOf("Pendapatan" to rupiah(s.dashboard.revenue),"Transaksi" to s.dashboard.transactions.toString(),"Laba Bersih" to rupiah(s.dashboard.netProfit),"Pengeluaran" to rupiah(s.dashboard.expenses)))};item{TopProducts(s.topProducts)};item{SakuCard{SectionTitle("Akses cepat");Spacer(Modifier.height(10.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Quick(Icons.Outlined.PointOfSale,"Kasir",Modifier.weight(1f)){vm.setPage(AppPage.CASHIER)};Quick(Icons.Outlined.Inventory2,"Produk",Modifier.weight(1f)){vm.setPage(AppPage.PRODUCTS)};Quick(Icons.Outlined.Analytics,"Laporan",Modifier.weight(1f)){vm.setPage(AppPage.REPORT)}}}}}}
@Composable private fun TopProducts(rows:List<TopProduct>){SakuCard{SectionTitle("3 Produk Terlaris");Spacer(Modifier.height(10.dp));if(rows.isEmpty())EmptyCompact(Icons.Outlined.BarChart,"Belum ada produk terlaris","Data muncul setelah transaksi selesai.")else{val pager=rememberPagerState(pageCount={rows.size});val context=LocalContext.current;LaunchedEffect(pager.currentPage,rows.size){if(rows.size>1&&motionEnabled(context)){delay(4000);pager.animateScrollToPage((pager.currentPage+1)%rows.size)}};HorizontalPager(pager,Modifier.fillMaxWidth()){i->val p=rows[i];Surface(shape=M,color=MaterialTheme.colorScheme.surfaceVariant,modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){ProductGlyph(p.name,82.dp);Spacer(Modifier.width(14.dp));Column(Modifier.weight(1f)){Kicker("#${i+1} PRODUK TERLARIS");Text(p.name,fontWeight=FontWeight.SemiBold,maxLines=2);Spacer(Modifier.height(8.dp));Text("Terjual ${p.quantitySold}",fontSize=11.sp);Text(rupiah(p.grossSales),fontSize=13.sp,fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.primary)}}}};Row(Modifier.fillMaxWidth().padding(top=8.dp),horizontalArrangement=Arrangement.Center){repeat(rows.size){i->Box(Modifier.padding(3.dp).size(if(i==pager.currentPage)18.dp else 6.dp,6.dp).clip(CircleShape).background(if(i==pager.currentPage)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.outlineVariant))}}}}}

@Composable private fun CashierScreen(s:AppSnapshot,f:UiFlags,vm:SakuViewModel){var open by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize()){HeroCompact("KASIR","Transaksi cepat","Pilih produk lalu selesaikan pembayaran");if(s.products.isEmpty())FullState(Icons.Outlined.Inventory2,"Belum ada produk","Tambahkan produk sebelum memulai transaksi.","Buka Produk"){vm.setPage(AppPage.PRODUCTS)}else{LazyVerticalGrid(GridCells.Fixed(2),Modifier.weight(1f).padding(horizontal=12.dp),contentPadding=PaddingValues(bottom=12.dp),horizontalArrangement=Arrangement.spacedBy(8.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){items(s.products,key={it.id}){p->ProductTile(p){vm.addCart(p)}}};val qty=f.cart.values.sum();Button({open=true},enabled=qty>0,modifier=Modifier.fillMaxWidth().padding(12.dp).heightIn(min=54.dp),shape=M){Icon(Icons.Outlined.ShoppingCart,null);Spacer(Modifier.width(8.dp));Text("Keranjang · $qty item")}}};if(open)CartSheet(s,f,{open=false},vm)}
@Composable private fun CartSheet(s:AppSnapshot,f:UiFlags,dismiss:()->Unit,vm:SakuViewModel){val selected=s.products.filter{f.cart.containsKey(it.id)};val total=selected.sumOf{it.sellPrice*(f.cart[it.id]?:0)};ModalBottomSheet(onDismissRequest=dismiss){Column(Modifier.fillMaxWidth().padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Konfirmasi transaksi",fontSize=22.sp,fontWeight=FontWeight.SemiBold);selected.forEach{p->Row(verticalAlignment=Alignment.CenterVertically){Text(p.name,Modifier.weight(1f),fontSize=12.sp);IconButton({vm.decCart(p.id)}){Icon(Icons.Outlined.Remove,null)};Text((f.cart[p.id]?:0).toString(),fontWeight=FontWeight.Bold);IconButton({vm.addCart(p)}){Icon(Icons.Outlined.Add,null)}}};HorizontalDivider();Row(horizontalArrangement=Arrangement.SpaceBetween,modifier=Modifier.fillMaxWidth()){Text("Total");Text(rupiah(total),fontWeight=FontWeight.Bold,fontSize=18.sp)};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(f.paymentMethod=="CASH",{vm.setPaymentMethod("CASH")},{Text("Tunai")},leadingIcon={Icon(Icons.Outlined.Payments,null)});FilterChip(f.paymentMethod=="QRIS",{vm.setPaymentMethod("QRIS")},{Text("QRIS")},leadingIcon={Icon(Icons.Outlined.QrCode2,null)})};Button({dismiss();vm.checkout()},Modifier.fillMaxWidth().heightIn(min=52.dp),shape=M){Text("Proses ${if(f.paymentMethod=="CASH")"Tunai" else "QRIS"}")};Spacer(Modifier.height(10.dp))}}}

@Composable private fun ProductsScreen(s:AppSnapshot,f:UiFlags,vm:SakuViewModel){var editor by remember{mutableStateOf<Product?>(null)};var add by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize()){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Produk & Stok",fontSize=24.sp,fontWeight=FontWeight.SemiBold);Text("${s.products.size} produk aktif",fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledIconButton({add=true}){Icon(Icons.Outlined.Add,"Tambah")}};OutlinedTextField(f.productQuery,vm::setProductQuery,Modifier.fillMaxWidth().padding(horizontal=16.dp),singleLine=true,leadingIcon={Icon(Icons.Outlined.Search,null)},placeholder={Text("Cari produk")},shape=M);Spacer(Modifier.height(10.dp));val rows=s.products.filter{it.name.contains(f.productQuery,true)};if(rows.isEmpty())FullState(Icons.Outlined.Inventory2,if(f.productQuery.isBlank())"Belum ada produk" else "Produk tidak ditemukan",if(f.productQuery.isBlank())"Tambahkan produk pertama Anda." else "Coba kata pencarian lain.","Tambah produk"){add=true}else LazyColumn(Modifier.weight(1f).padding(horizontal=16.dp),verticalArrangement=Arrangement.spacedBy(8.dp),contentPadding=PaddingValues(bottom=16.dp)){items(rows,key={it.id}){p->ProductRow(p){editor=p}}}};if(add)ProductSheet(null,{add=false},vm);editor?.let{ProductSheet(it,{editor=null},vm)}}
@Composable private fun ProductSheet(p:Product?,dismiss:()->Unit,vm:SakuViewModel){val ctx=LocalContext.current;val scope=rememberCoroutineScope();var d by remember(p){mutableStateOf(ProductDraft(p?.id,p?.name?:"",p?.buyPrice?.toString()?:"0",p?.sellPrice?.toString()?:"0",p?.stock?.toString()?:"0",p?.minStock?.toString()?:"5"))};val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){uri->if(uri!=null)scope.launch{runCatching{vm.prepareImage(ctx.contentResolver,uri)}.onSuccess{(b,m)->d=d.copy(imageBytes=b,imageMime=m)}}};ModalBottomSheet(onDismissRequest=dismiss){Column(Modifier.fillMaxWidth().verticalScroll(rememberScrollState()).padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(if(p==null)"Tambah produk" else "Edit produk",fontSize=22.sp,fontWeight=FontWeight.SemiBold);OutlinedButton({picker.launch("image/*")},Modifier.fillMaxWidth(),shape=M){Icon(Icons.Outlined.AddAPhoto,null);Spacer(Modifier.width(8.dp));Text(if(d.imageBytes!=null)"Foto siap digunakan" else if(p==null)"Pilih foto produk (wajib)" else "Ganti foto (opsional)")};Field(d.name,{d=d.copy(name=it)},"Nama produk",Icons.Outlined.Inventory2);Field(d.buyPrice,{d=d.copy(buyPrice=it)},"Harga beli",Icons.Outlined.Payments,KeyboardType.Number);Field(d.sellPrice,{d=d.copy(sellPrice=it)},"Harga jual",Icons.Outlined.Sell,KeyboardType.Number);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Box(Modifier.weight(1f)){Field(d.stock,{d=d.copy(stock=it)},"Stok",Icons.Outlined.Inventory,KeyboardType.Number)};Box(Modifier.weight(1f)){Field(d.minStock,{d=d.copy(minStock=it)},"Batas rendah",Icons.Outlined.WarningAmber,KeyboardType.Number)}};Button({vm.saveProduct(d);dismiss()},Modifier.fillMaxWidth().heightIn(min=52.dp),shape=M){Text("Simpan produk")};if(p!=null)OutlinedButton({vm.deleteProduct(p.id);dismiss()},Modifier.fillMaxWidth(),shape=M,colors=ButtonDefaults.outlinedButtonColors(contentColor=MaterialTheme.colorScheme.error)){Text("Nonaktifkan produk")};Spacer(Modifier.height(10.dp))}}}

@Composable private fun ReportScreen(s:AppSnapshot,f:UiFlags,vm:SakuViewModel){val r=f.report;val ctx=LocalContext.current;var expense by remember{mutableStateOf(false)};LazyColumn(Modifier.fillMaxSize().padding(horizontal=16.dp),verticalArrangement=Arrangement.spacedBy(11.dp),contentPadding=PaddingValues(bottom=20.dp)){item{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("Laporan & Analisis",fontSize=24.sp,fontWeight=FontWeight.SemiBold);Text("Pendapatan − HPP − Pengeluaran = Laba Bersih",fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)};FilledTonalIconButton({r?.let{ReportExporter.exportAndShare(ctx,s.merchant.name,it)}},enabled=r!=null){Icon(Icons.Outlined.PictureAsPdf,"Bagikan PDF")}}};item{LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){items(listOf("daily" to "Harian","weekly" to "Mingguan","monthly" to "Bulanan","yearly" to "Tahunan")){(v,l)->FilterChip(f.reportPeriod==v,{vm.loadReport(v)},{Text(l)})}}};if(r==null)item{Skeleton(180.dp)}else{item{MetricGrid(listOf("Pendapatan" to rupiah(r.revenue),"HPP" to rupiah(r.cogs),"Pengeluaran" to rupiah(r.expenses),"Laba Bersih" to rupiah(r.netProfit)))};item{SakuCard{SectionTitle("Metode pembayaran");if(r.payments.isEmpty())EmptyCompact(Icons.Outlined.Payments,"Belum ada transaksi","Data muncul setelah transaksi selesai.")else r.payments.forEach{x->Row(Modifier.fillMaxWidth().padding(vertical=7.dp)){Text(x.method,Modifier.weight(1f));Text(rupiah(x.amount),fontWeight=FontWeight.SemiBold)}}}};item{SakuCard{SectionTitle("Pengeluaran");if(f.expenses.isEmpty())EmptyCompact(Icons.Outlined.ReceiptLong,"Belum ada pengeluaran","Catat biaya agar laba bersih lebih akurat.")else f.expenses.take(30).forEach{x->Row(Modifier.fillMaxWidth().padding(vertical=7.dp)){Text(x.description.ifBlank{x.category},Modifier.weight(1f),fontSize=11.sp);Text(rupiah(x.amount),fontSize=11.sp,fontWeight=FontWeight.SemiBold)}};OutlinedButton({expense=true},Modifier.fillMaxWidth()){Text("Catat pengeluaran")}}}}};if(expense)ExpenseSheet({expense=false},vm)}
@Composable private fun ExpenseSheet(dismiss:()->Unit,vm:SakuViewModel){var d by remember{mutableStateOf("")};var c by remember{mutableStateOf("Operasional")};var a by remember{mutableStateOf("")};ModalBottomSheet(onDismissRequest=dismiss){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Catat pengeluaran",fontSize=22.sp,fontWeight=FontWeight.SemiBold);Field(d,{d=it},"Deskripsi",Icons.Outlined.ReceiptLong);Field(c,{c=it},"Kategori",Icons.Outlined.Category);Field(a,{a=it},"Jumlah",Icons.Outlined.Payments,KeyboardType.Number);Button({vm.addExpense(d,c,a.toLongOrNull()?:0);dismiss()},enabled=(a.toLongOrNull()?:0)>0,modifier=Modifier.fillMaxWidth()){Text("Simpan")};Spacer(Modifier.height(10.dp))}}}

@Composable private fun AccountScreen(s:AppSnapshot,f:UiFlags,vm:SakuViewModel){var edit by remember{mutableStateOf(false)};var password by remember{mutableStateOf(false)};LazyColumn(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Hero("AKUN",s.user.name,s.user.email)};item{SakuCard{Text(s.merchant.name,fontSize=18.sp,fontWeight=FontWeight.SemiBold);Text(s.merchant.businessCategory,fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(10.dp));OutlinedButton({edit=true},Modifier.fillMaxWidth()){Text("Edit profil usaha")}}};item{SakuCard{Row(verticalAlignment=Alignment.CenterVertically){Icon(Icons.Outlined.DarkMode,null);Spacer(Modifier.width(10.dp));Text("Mode gelap",Modifier.weight(1f));Switch(f.darkMode,vm::setDarkMode)};HorizontalDivider(Modifier.padding(vertical=8.dp));TextButton({password=true}){Text("Ubah password")};TextButton({vm.logout()},colors=ButtonDefaults.textButtonColors(contentColor=MaterialTheme.colorScheme.error)){Text("Keluar")}}}};if(edit)MerchantSheet(s.merchant,{edit=false},vm);if(password)PasswordSheet({password=false},vm)}
@Composable private fun MerchantSheet(m:Merchant,dismiss:()->Unit,vm:SakuViewModel){var n by remember{mutableStateOf(m.name)};var c by remember{mutableStateOf(m.businessCategory)};var p by remember{mutableStateOf(m.phoneNumber)};var a by remember{mutableStateOf(m.address)};var b by remember{mutableStateOf(m.businessBio)};ModalBottomSheet(onDismissRequest=dismiss){Column(Modifier.fillMaxWidth().verticalScroll(rememberScrollState()).padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Profil usaha",fontSize=22.sp,fontWeight=FontWeight.SemiBold);Field(n,{n=it},"Nama usaha",Icons.Outlined.Storefront);Field(c,{c=it},"Kategori",Icons.Outlined.Category);Field(p,{p=it},"Telepon",Icons.Outlined.Phone);Field(a,{a=it},"Alamat",Icons.Outlined.LocationOn,single=false);Field(b,{b=it},"Tentang usaha",Icons.Outlined.Description,single=false);Button({vm.updateMerchant(n,c,p,a,b);dismiss()},enabled=n.length>=2,modifier=Modifier.fillMaxWidth()){Text("Simpan perubahan")};Spacer(Modifier.height(10.dp))}}}
@Composable private fun PasswordSheet(dismiss:()->Unit,vm:SakuViewModel){var cur by remember{mutableStateOf("")};var next by remember{mutableStateOf("")};ModalBottomSheet(onDismissRequest=dismiss){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Ubah password",fontSize=22.sp,fontWeight=FontWeight.SemiBold);Field(cur,{cur=it},"Password saat ini",Icons.Outlined.Lock,password=true);Field(next,{next=it},"Password baru (min. 12 karakter)",Icons.Outlined.Key,password=true);Button({vm.changePassword(cur,next);dismiss()},enabled=cur.isNotBlank()&&next.length>=12,modifier=Modifier.fillMaxWidth()){Text("Ubah password")};Spacer(Modifier.height(10.dp))}}}

@Composable private fun Hero(k:String,t:String,b:String){Column(Modifier.padding(vertical=8.dp)){Kicker(k);Text(t,fontSize=27.sp,fontWeight=FontWeight.SemiBold);Text(b,fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
@Composable private fun HeroCompact(k:String,t:String,b:String){Column(Modifier.padding(horizontal=16.dp,vertical=8.dp)){Kicker(k);Text(t,fontSize=24.sp,fontWeight=FontWeight.SemiBold);Text(b,fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
@Composable private fun Kicker(t:String){Text(t.uppercase(),fontSize=10.sp,fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.primary)}
@Composable private fun MetricGrid(rows:List<Pair<String,String>>){Column(verticalArrangement=Arrangement.spacedBy(8.dp)){rows.chunked(2).forEach{pair->Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){pair.forEach{(l,v)->Surface(shape=M,color=MaterialTheme.colorScheme.surface,border=androidx.compose.foundation.BorderStroke(1.dp,MaterialTheme.colorScheme.outlineVariant),modifier=Modifier.weight(1f)){Column(Modifier.padding(14.dp)){Text(l,fontSize=10.sp,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(v,fontSize=16.sp,fontWeight=FontWeight.Bold,maxLines=1,overflow=TextOverflow.Ellipsis)}}};if(pair.size==1)Spacer(Modifier.weight(1f))}}}}
@Composable private fun SectionTitle(t:String){Text(t,fontSize=14.sp,fontWeight=FontWeight.SemiBold)}
@Composable private fun Quick(icon:ImageVector,label:String,mod:Modifier,on:()->Unit){FilledTonalButton(on,modifier=mod,contentPadding=PaddingValues(vertical=11.dp)){Icon(icon,null,Modifier.size(18.dp));Spacer(Modifier.width(5.dp));Text(label,fontSize=10.sp)}}
@Composable private fun ProductTile(p:Product,on:()->Unit){Surface(onClick=on,shape=M,color=MaterialTheme.colorScheme.surface,border=androidx.compose.foundation.BorderStroke(1.dp,MaterialTheme.colorScheme.outlineVariant)){Column(Modifier.padding(11.dp)){ProductGlyph(p.name,82.dp);Spacer(Modifier.height(8.dp));Text(p.name,fontSize=12.sp,fontWeight=FontWeight.SemiBold,maxLines=2,minLines=2);Text(rupiah(p.sellPrice),fontSize=12.sp,fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.primary);Text("Stok ${p.stock}",fontSize=10.sp,color=if(p.stock<=p.minStock)SakuColors.Warning else MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable private fun ProductRow(p:Product,on:()->Unit){Surface(onClick=on,shape=M,color=MaterialTheme.colorScheme.surface,border=androidx.compose.foundation.BorderStroke(1.dp,MaterialTheme.colorScheme.outlineVariant),modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(11.dp),verticalAlignment=Alignment.CenterVertically){ProductGlyph(p.name,58.dp);Spacer(Modifier.width(11.dp));Column(Modifier.weight(1f)){Text(p.name,fontWeight=FontWeight.SemiBold,fontSize=12.sp);Text(rupiah(p.sellPrice),fontWeight=FontWeight.Bold,fontSize=12.sp,color=MaterialTheme.colorScheme.primary);Text("Stok ${p.stock} · HPP ${rupiah(p.buyPrice)}",fontSize=10.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)};if(p.stock<=p.minStock)Icon(Icons.Outlined.WarningAmber,"Stok rendah",tint=SakuColors.Warning)}}}
@Composable private fun ProductGlyph(name:String,size:androidx.compose.ui.unit.Dp){Box(Modifier.size(size).clip(M).background(MaterialTheme.colorScheme.primaryContainer),contentAlignment=Alignment.Center){Text(name.trim().take(2).uppercase().ifBlank{"SA"},fontSize=(size.value*.24f).sp,fontWeight=FontWeight.Bold,color=MaterialTheme.colorScheme.primary)}}
@Composable private fun WalletMark(size:androidx.compose.ui.unit.Dp){Image(painterResource(R.drawable.saku_official_logo),"SAKU",Modifier.size(size))}
@Composable private fun SakuCard(content:@Composable ColumnScope.()->Unit){Surface(shape=L,color=MaterialTheme.colorScheme.surface,border=androidx.compose.foundation.BorderStroke(1.dp,MaterialTheme.colorScheme.outlineVariant),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),content=content)}}
@Composable private fun Field(value:String,on:(String)->Unit,label:String,icon:ImageVector,keyboard:KeyboardType=KeyboardType.Text,single:Boolean=true,password:Boolean=false){OutlinedTextField(value,on,Modifier.fillMaxWidth().semantics{contentDescription=label},label={Text(label)},leadingIcon={Icon(icon,null)},singleLine=single,minLines=if(single)1 else 3,keyboardOptions=KeyboardOptions(keyboardType=keyboard),visualTransformation=if(password)PasswordVisualTransformation() else androidx.compose.ui.text.input.VisualTransformation.None,shape=M)}
@Composable private fun InlineMessage(t:String){Surface(shape=S,color=MaterialTheme.colorScheme.errorContainer){Row(Modifier.fillMaxWidth().padding(10.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Outlined.ErrorOutline,null,tint=MaterialTheme.colorScheme.error);Spacer(Modifier.width(8.dp));Text(t,fontSize=11.sp,color=MaterialTheme.colorScheme.onErrorContainer)}}}
@Composable private fun EmptyCompact(icon:ImageVector,title:String,body:String){Column(Modifier.fillMaxWidth().padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(icon,null,tint=MaterialTheme.colorScheme.primary);Spacer(Modifier.height(8.dp));Text(title,fontWeight=FontWeight.SemiBold);Text(body,fontSize=10.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}}
@Composable private fun FullState(icon:ImageVector,title:String,body:String,cta:String,on:()->Unit){Box(Modifier.fillMaxSize().padding(24.dp),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(icon,null,Modifier.size(34.dp),tint=MaterialTheme.colorScheme.primary);Spacer(Modifier.height(12.dp));Text(title,fontSize=19.sp,fontWeight=FontWeight.SemiBold);Text(body,fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(12.dp));Button(on){Text(cta)}}}}
@Composable private fun BrandedLoading(t:String){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){WalletMark(68.dp);Spacer(Modifier.height(16.dp));CircularProgressIndicator(Modifier.size(22.dp),strokeWidth=2.dp);Spacer(Modifier.height(10.dp));Text(t,fontSize=11.sp,color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable private fun Skeleton(h:androidx.compose.ui.unit.Dp){Box(Modifier.fillMaxWidth().height(h).clip(L).background(MaterialTheme.colorScheme.surfaceVariant))}
private fun motionEnabled(c:Context)=runCatching{Settings.Global.getFloat(c.contentResolver,Settings.Global.ANIMATOR_DURATION_SCALE,1f)>0f}.getOrDefault(true)
